import type { MetadataRoute } from 'next'

export default function sitemap(): MetadataRoute.Sitemap {
  return [
    {
      url: 'https://mageui.live/',
      lastModified: new Date(),
      changeFrequency: 'yearly',
      priority: 1,
    },
    {
      url: 'https://mageui.live/docs/changelog',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://mageui.live/docs/',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.5,
    },
    {
      url: 'https://mageui.live/docs/setup',
      lastModified: new Date(),
      changeFrequency: 'yearly',
      priority: 1,
    },
    {
      url: 'https://mageui.live/docs/accordion/faq',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://mageui.live/docs/background/animated-beam',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.5,
    },
    {
      url: 'https://mageui.live/docs/background/blurry-blob',
      lastModified: new Date(),
      changeFrequency: 'yearly',
      priority: 1,
    },
    {
      url: 'https://mageui.live/docs/background/diagonal-lines',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://mageui.live/docs/background/dot',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.5,
    },
    {
      url: 'https://mageui.live/docs/background/grid',
      lastModified: new Date(),
      changeFrequency: 'yearly',
      priority: 1,
    },
    {
      url: 'https://mageui.live/docs/background/hero-parallax',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://mageui.live/docs/background/interactive-grid',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.5,
    },
    {
      url: 'https://mageui.live/docs/background/lamp',
      lastModified: new Date(),
      changeFrequency: 'yearly',
      priority: 1,
    },
    {
      url: 'https://mageui.live/docs/background/moving-gradient',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://mageui.live/docs/background/sparkles',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.5,
    },
    {
      url: 'https://mageui.live/docs/background/zigzag',
      lastModified: new Date(),
      changeFrequency: 'yearly',
      priority: 1,
    },
    {
      url: 'https://mageui.live/docs/bento-grid/eight',
      lastModified: new Date(),
      changeFrequency: 'yearly',
      priority: 1,
    },
    {
      url: 'https://mageui.live/docs/bento-grid/glowing-bento',
      lastModified: new Date(),
      changeFrequency: 'yearly',
      priority: 1,
    },
    {
      url: 'https://mageui.live/docs/bento-grid/gradient',
      lastModified: new Date(),
      changeFrequency: 'yearly',
      priority: 1,
    },
    {
      url: 'https://mageui.live/docs/bento-grid',
      lastModified: new Date(),
      changeFrequency: 'yearly',
      priority: 1,
    },
    {
      url: 'https://mageui.live/docs/bento-grid/three',
      lastModified: new Date(),
      changeFrequency: 'yearly',
      priority: 1,
    },
    {
      url: 'https://mageui.live/docs/button/ai-button',
      lastModified: new Date(),
      changeFrequency: 'yearly',
      priority: 1,
    },
    {
      url: 'https://mageui.live/docs/button/algolia-blue-button',
      lastModified: new Date(),
      changeFrequency: 'yearly',
      priority: 1,
    },
    {
      url: 'https://mageui.live/docs/button/algolia-white-button',
      lastModified: new Date(),
      changeFrequency: 'yearly',
      priority: 1,
    },
    {
      url: 'https://mageui.live/docs/button/duolingo',
      lastModified: new Date(),
      changeFrequency: 'yearly',
      priority: 1,
    },
    {
      url: 'https://mageui.live/docs/button/external-link-button',
      lastModified: new Date(),
      changeFrequency: 'yearly',
      priority: 1,
    },
    {
      url: 'https://mageui.live/docs/button/get-started-button',
      lastModified: new Date(),
      changeFrequency: 'yearly',
      priority: 1,
    },
    {
      url: 'https://mageui.live/docs/button/hover-border-gradient',
      lastModified: new Date(),
      changeFrequency: 'yearly',
      priority: 1,
    },
    {
      url: 'https://mageui.live/docs/button',
      lastModified: new Date(),
      changeFrequency: 'yearly',
      priority: 1,
    },
    {
      url: 'https://mageui.live/docs/button/moving-border',
      lastModified: new Date(),
      changeFrequency: 'yearly',
      priority: 1,
    },
    {
      url: 'https://mageui.live/docs/button/ripple-button',
      lastModified: new Date(),
      changeFrequency: 'yearly',
      priority: 1,
    },
    {
      url: 'https://mageui.live/docs/button/shining-button',
      lastModified: new Date(),
      changeFrequency: 'yearly',
      priority: 1,
    },
    {
      url: 'https://mageui.live/docs/button/slide-arrow-button',
      lastModified: new Date(),
      changeFrequency: 'yearly',
      priority: 1,
    },
    {
      url: 'https://mageui.live/docs/button/status-button',
      lastModified: new Date(),
      changeFrequency: 'yearly',
      priority: 1,
    },
    {
      url: 'https://mageui.live/docs/button/swipe-button',
      lastModified: new Date(),
      changeFrequency: 'yearly',
      priority: 1,
    },
    {
      url: 'https://mageui.live/docs/button/toggle-switch',
      lastModified: new Date(),
      changeFrequency: 'yearly',
      priority: 1,
    },
    {
      url: 'https://mageui.live/docs/button/work-button',
      lastModified: new Date(),
      changeFrequency: 'yearly',
      priority: 1,
    },
    {
      url: 'https://mageui.live/docs/card/animated-testimonials',
      lastModified: new Date(),
      changeFrequency: 'yearly',
      priority: 1,
    },
    {
      url: 'https://mageui.live/docs/card/card-comment',
      lastModified: new Date(),
      changeFrequency: 'yearly',
      priority: 1,
    },
    {
      url: 'https://mageui.live/docs/card/card-spread',
      lastModified: new Date(),
      changeFrequency: 'yearly',
      priority: 1,
    },
    {
      url: 'https://mageui.live/docs/card/card-stack',
      lastModified: new Date(),
      changeFrequency: 'yearly',
      priority: 1,
    },
    {
      url: 'https://mageui.live/docs/card/case-study-card',
      lastModified: new Date(),
      changeFrequency: 'yearly',
      priority: 1,
    },
    {
      url: 'https://mageui.live/docs/card/comment-reply-card',
      lastModified: new Date(),
      changeFrequency: 'yearly',
      priority: 1,
    },
    {
      url: 'https://mageui.live/docs/card/direction-aware-hover',
      lastModified: new Date(),
      changeFrequency: 'yearly',
      priority: 1,
    },

    {
      url: 'https://mageui.live/docs/card/email-feature-card',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://mageui.live/docs/card/evervault-card',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://mageui.live/docs/card/flip-card',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://mageui.live/docs/card/fluid-tabs',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://mageui.live/docs/card/github-card-shiny',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://mageui.live/docs/card/github-card-skew',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://mageui.live/docs/card/glowing-card',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://mageui.live/docs/card/hover-effect',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://mageui.live/docs/card/integration-pills',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://mageui.live/docs/card/led-board',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://mageui.live/docs/card/notice-card',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://mageui.live/docs/card/notification-card',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://mageui.live/docs/card/notify-user-info',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://mageui.live/docs/card/reminder-scheduler',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://mageui.live/docs/card/score-card',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://mageui.live/docs/card/staggered-card',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://mageui.live/docs/card/stars-card',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://mageui.live/docs/card/subscribe-card',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://mageui.live/docs/card/survey-card',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://mageui.live/docs/card/swap-card',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://mageui.live/docs/card/swap-text-card',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://mageui.live/docs/card/three-d-card-effect',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://mageui.live/docs/card/three-d-pin',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://mageui.live/docs/card/tilted-card',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://mageui.live/docs/card/webhooks-card',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://mageui.live/docs/carousel/carousel',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://mageui.live/docs/carousel/expandable',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://mageui.live/docs/carousel/image-carousel',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://mageui.live/docs/container/animated-border-trail',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://mageui.live/docs/container/animated-dock',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://mageui.live/docs/container/cursor-tracker',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://mageui.live/docs/container/fibonacci-lines',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://mageui.live/docs/container/marquee',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://mageui.live/docs/container/nav-tabs',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://mageui.live/docs/container/scrolling-testimonials',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://mageui.live/docs/container/shift-tabs',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://mageui.live/docs/cursor-effects/arrow-cursor-effect',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://mageui.live/docs/cursor-effects/bubble-cursor',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://mageui.live/docs/cursor-effects/canvas-cursor-effect',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://mageui.live/docs/cursor-effects/character-cursor-effect',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://mageui.live/docs/cursor-effects/trail-cursor-effect',
      lastModified: new Date('2025-03-20T03:16:56.829Z'),
      changeFrequency: 'weekly',
      priority: 0.5,
    },
    {
      url: 'https://mageui.live/docs/fabs/speed-dial',
      lastModified: new Date('2025-03-20T03:16:56.829Z'),
      changeFrequency: 'weekly',
      priority: 0.5,
    },
    {
      url: 'https://mageui.live/docs/feature-cards/confirmation-message',
      lastModified: new Date('2025-03-20T03:16:56.829Z'),
      changeFrequency: 'weekly',
      priority: 0.5,
    },
    {
      url: 'https://mageui.live/docs/feature-cards/content-scan',
      lastModified: new Date('2025-03-20T03:16:56.829Z'),
      changeFrequency: 'weekly',
      priority: 0.5,
    },
    {
      url: 'https://mageui.live/docs/graphs/bar-chart',
      lastModified: new Date('2025-03-20T03:16:56.829Z'),
      changeFrequency: 'weekly',
      priority: 0.5,
    },
    {
      url: 'https://mageui.live/docs/graphs/commit-graph',
      lastModified: new Date('2025-03-20T03:16:56.829Z'),
      changeFrequency: 'weekly',
      priority: 0.5,
    },
    {
      url: 'https://mageui.live/docs/graphs/donut-chart',
      lastModified: new Date('2025-03-20T03:16:56.829Z'),
      changeFrequency: 'weekly',
      priority: 0.5,
    },
    {
      url: 'https://mageui.live/docs/graphs/gauge-chart',
      lastModified: new Date('2025-03-20T03:16:56.829Z'),
      changeFrequency: 'weekly',
      priority: 0.5,
    },
    {
      url: 'https://mageui.live/docs/graphs',
      lastModified: new Date('2025-03-20T03:16:56.829Z'),
      changeFrequency: 'weekly',
      priority: 0.5,
    },
    {
      url: 'https://mageui.live/docs/graphs/progress',
      lastModified: new Date('2025-03-20T03:16:56.829Z'),
      changeFrequency: 'weekly',
      priority: 0.5,
    },
    {
      url: 'https://mageui.live/docs/graphs/ring-chart',
      lastModified: new Date('2025-03-20T03:16:56.829Z'),
      changeFrequency: 'weekly',
      priority: 0.5,
    },
    {
      url: 'https://mageui.live/docs/widget/calendar-event',
      lastModified: new Date('2025-03-20T03:16:56.833Z'),
      changeFrequency: 'weekly',
      priority: 0.5,
    },
    {
      url: 'https://mageui.live/docs/widget/calorie-counter',
      lastModified: new Date('2025-03-20T03:16:56.833Z'),
      changeFrequency: 'weekly',
      priority: 0.5,
    },
    {
      url: 'https://mageui.live/docs/widget/clock-with-photo',
      lastModified: new Date('2025-03-20T03:16:56.833Z'),
      changeFrequency: 'weekly',
      priority: 0.5,
    },
    {
      url: 'https://mageui.live/docs/widget/cycling',
      lastModified: new Date('2025-03-20T03:16:56.833Z'),
      changeFrequency: 'weekly',
      priority: 0.5,
    },
    {
      url: 'https://mageui.live/docs/widget/delivery-card',
      lastModified: new Date('2025-03-20T03:16:56.833Z'),
      changeFrequency: 'weekly',
      priority: 0.5,
    },
    {
      url: 'https://mageui.live/docs/widget/direction-card',
      lastModified: new Date('2025-03-20T03:16:56.833Z'),
      changeFrequency: 'weekly',
      priority: 0.5,
    },
    {
      url: 'https://mageui.live/docs/widget/expense-tracker',
      lastModified: new Date('2025-03-20T03:16:56.833Z'),
      changeFrequency: 'weekly',
      priority: 0.5,
    },
    {
      url: 'https://mageui.live/docs/widget/file-upload',
      lastModified: new Date('2025-03-20T03:16:56.833Z'),
      changeFrequency: 'weekly',
      priority: 0.5,
    },
    {
      url: 'https://mageui.live/docs/widget/flight-widget',
      lastModified: new Date('2025-03-20T03:16:56.833Z'),
      changeFrequency: 'weekly',
      priority: 0.5,
    },
    {
      url: 'https://mageui.live/docs/widget/fund-widget',
      lastModified: new Date('2025-03-20T03:16:56.833Z'),
      changeFrequency: 'weekly',
      priority: 0.5,
    },
    {
      url: 'https://mageui.live/docs/widget/live-score',
      lastModified: new Date('2025-03-20T03:16:56.833Z'),
      changeFrequency: 'weekly',
      priority: 0.5,
    },
    {
      url: 'https://mageui.live/docs/widget/mobile-detail',
      lastModified: new Date('2025-03-20T03:16:56.833Z'),
      changeFrequency: 'weekly',
      priority: 0.5,
    },
    {
      url: 'https://mageui.live/docs/widget/music-stack-interaction',
      lastModified: new Date('2025-03-20T03:16:56.833Z'),
      changeFrequency: 'weekly',
      priority: 0.5,
    },
    {
      url: 'https://mageui.live/docs/widget/music-widget',
      lastModified: new Date('2025-03-20T03:16:56.833Z'),
      changeFrequency: 'weekly',
      priority: 0.5,
    },
    {
      url: 'https://mageui.live/docs/widget/notes',
      lastModified: new Date('2025-03-20T03:16:56.833Z'),
      changeFrequency: 'weekly',
      priority: 0.5,
    },
    {
      url: 'https://mageui.live/docs/widget/profile',
      lastModified: new Date('2025-03-20T03:16:56.833Z'),
      changeFrequency: 'weekly',
      priority: 0.5,
    },
    {
      url: 'https://mageui.live/docs/widget/reminder-widget',
      lastModified: new Date('2025-03-20T03:16:56.833Z'),
      changeFrequency: 'weekly',
      priority: 0.5,
    },
    {
      url: 'https://mageui.live/docs/widget/reminder',
      lastModified: new Date('2025-03-20T03:16:56.833Z'),
      changeFrequency: 'weekly',
      priority: 0.5,
    },
    {
      url: 'https://mageui.live/docs/widget/score-board',
      lastModified: new Date('2025-03-20T03:16:56.833Z'),
      changeFrequency: 'weekly',
      priority: 0.5,
    },
    {
      url: 'https://mageui.live/docs/widget/security-alert',
      lastModified: new Date('2025-03-20T03:16:56.833Z'),
      changeFrequency: 'weekly',
      priority: 0.5,
    },
    {
      url: 'https://mageui.live/docs/widget/shifting-countdown',
      lastModified: new Date('2025-03-20T03:16:56.833Z'),
      changeFrequency: 'weekly',
      priority: 0.5,
    },
    {
      url: 'https://mageui.live/docs/widget/shopping-list',
      lastModified: new Date('2025-03-20T03:16:56.833Z'),
      changeFrequency: 'weekly',
      priority: 0.5,
    },
    {
      url: 'https://mageui.live/docs/widget/sleep-tracker',
      lastModified: new Date('2025-03-20T03:16:56.833Z'),
      changeFrequency: 'weekly',
      priority: 0.5,
    },
    {
      url: 'https://mageui.live/docs/widget/storage-status',
      lastModified: new Date('2025-03-20T03:16:56.833Z'),
      changeFrequency: 'weekly',
      priority: 0.5,
    },
    {
      url: 'https://mageui.live/docs/widget/storage-widget',
      lastModified: new Date('2025-03-20T03:16:56.833Z'),
      changeFrequency: 'weekly',
      priority: 0.5,
    },
    {
      url: 'https://mageui.live/docs/widget/study-timer',
      lastModified: new Date('2025-03-20T03:16:56.833Z'),
      changeFrequency: 'weekly',
      priority: 0.5,
    },
    {
      url: 'https://mageui.live/docs/widget/team-clock',
      lastModified: new Date('2025-03-20T03:16:56.833Z'),
      changeFrequency: 'weekly',
      priority: 0.5,
    },
    {
      url: 'https://mageui.live/docs/widget/video-chat',
      lastModified: new Date('2025-03-20T03:16:56.833Z'),
      changeFrequency: 'weekly',
      priority: 0.5,
    },
    {
      url: 'https://mageui.live/docs/widget/vpn-widget',
      lastModified: new Date('2025-03-20T03:16:56.833Z'),
      changeFrequency: 'weekly',
      priority: 0.5,
    },
    {
      url: 'https://mageui.live/docs/widget/water-tracker',
      lastModified: new Date('2025-03-20T03:16:56.833Z'),
      changeFrequency: 'weekly',
      priority: 0.5,
    },
    {
      url: 'https://mageui.live/docs/widget/weather-card',
      lastModified: new Date('2025-03-20T03:16:56.833Z'),
      changeFrequency: 'weekly',
      priority: 0.5,
    },
    {
      url: 'https://mageui.live/docs/widget/weekly-progress',
      lastModified: new Date('2025-03-20T03:16:56.833Z'),
      changeFrequency: 'weekly',
      priority: 0.5,
    }
  ]
}